version: 2
plan:
  project-key: JP
  name: Mrim
  key: MRIM

variables:
  deployUsername: admin
  deployPassword: BAMSCRT@0@0@8AmEg368NEmtiY1OBzXgxA==
  jiraBaseUrl: localhost:2990/jira

stages:
  - Build:
      jobs:
        - Build jar
  - Deploy to jira:
      manual: true
      jobs:
        - Deploy jar
  - Cleanup:
      final: true
      jobs:
        - Cleanup
Build jar:
  tasks:
    - script:
        - atlas-clean & atlas-package
  artifacts:
    - name: mrimsender
      location: target
      pattern: '*.jar'
      required: true
      shared: true

Deploy jar:
  tasks:
    - script:
        - ./deployPlugin.sh

Cleanup:
  tasks:
    - clean
    - script:
        - atlas-clean